version: '3'

networks:
  development:
  production:
services:
#  account:
#    build:
#      context: ./services/account
#    depends_on:
#      - localstack
#      - vault-development
#    links:
#      - localstack
#    environment:
#      - ENVIRONMENT=development
  localstack:
    networks:
      - development
      - production
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.0.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  vault-development:
    networks:
      - development
    image: vault:1.8.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=f23612cf-824d-4206-9e94-e31a6dc8ee8d
    # production    
  vault-production:
    networks:
      - production
    image: vault:1.8.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8301:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=083672fc-4471-4ec4-9b59-a285e463a973
